### ISSUE TITLE
Critical Error: Failed to download the language server.

### ISSUE THREAD

**Issue by Erroman** [Exafunction/CodeiumVisualStudio#70] opened 2024-04-12 18:53 UTC
After the update to Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.9.6
Codeium gives this error: 
Critical Error: Failed to download the language server. Do you want to retry ?
Retry doesn't help.
People on Discord report the same issue, nobody suggesting any remedy.

**Comment by fortenforge** [comment] 2024-04-12 18:55
Duplicate of https://github.com/Exafunction/CodeiumVisualStudio/issues/69

I'm working on it.

**Closed by fortenforge** 2024-04-12 18:55 UTC
